import React from 'react';

export const AppFooter = ({ className = '' }) => (
    <footer className={`app-global-footer ${className}`.trim()}>
        <hr className="app-global-footer__rule" />
        <div className="app-global-footer__text">
            <span>Generated by Chesslyze</span>
            <span>Your journey continues with every move.</span>
        </div>
    </footer>
);
